name: 'Tests: node.js'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^18.16.0 || ^20.2.0'
      type: minors
      command: npm run tests-only

  node:
    name: 'node (engines.node)'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
